import { CartItem, PaymentMethod, SavedAddress, ShippingOption } from "@/types/checkout";

export const CART_ITEMS: CartItem[] = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    brand: "TechSound",
    price: 79.99,
    originalPrice: 99.99,
    image: "/placeholder.svg?height=300&width=300",
    quantity: 2,
    inStock: true,
    category: "Electronics",
  },
  {
    id: 2,
    name: "Organic Cotton T-Shirt",
    brand: "EcoWear",
    price: 24.99,
    originalPrice: 29.99,
    image: "/placeholder.svg?height=300&width=300",
    quantity: 1,
    inStock: true,
    category: "Clothing",
  },
]


export const SAVED_ADDRESSES: SavedAddress[] = [
  {
    id: "addr_1",
    label: "Home",
    firstName: "John",
    lastName: "Doe",
    address: "123 Main Street",
    apartment: "Apt 4B",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    country: "US",
    isDefault: true,
    phone: "(555) 123-4567",
  },
  {
    id: "addr_2",
    label: "Work",
    firstName: "John",
    lastName: "Doe",
    address: "456 Business Ave",
    city: "New York",
    state: "NY",
    zipCode: "10002",
    country: "US",
    isDefault: false,
    phone: "(555) 987-6543",
  },
  {
    id: "addr_3",
    label: "Mom's House",
    firstName: "John",
    lastName: "Doe",
    address: "789 Family Lane",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11201",
    country: "US",
    isDefault: false,
    phone: "(555) 456-7890",
  },
]


export const US_STATES = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
]

export const SHIPPING_OPTIONS: ShippingOption[] = [
  { id: "standard", name: "Standard Shipping", price: 5.99, days: "5-7 business days" },
  { id: "express", name: "Express Shipping", price: 12.99, days: "2-3 business days" },
  { id: "overnight", name: "Overnight Shipping", price: 24.99, days: "Next business day" },
]

export const PAYMENT_METHODS: PaymentMethod[] = [
  { id: "credit", type: "credit", name: "Credit Card", icon: "💳" },
  { id: "debit", type: "debit", name: "Debit Card", icon: "💳" },
  { id: "paypal", type: "paypal", name: "PayPal", icon: "🅿️" },
  { id: "apple_pay", type: "apple_pay", name: "Apple Pay", icon: "🍎" },
  { id: "google_pay", type: "google_pay", name: "Google Pay", icon: "🔵" },
]