import { Order } from '@/types/order';

// Mock data
export const MockOrders: Order[] = [
  {
    id: 'ORD-001',
    date: '2024-01-15',
    buyerName: 'John Doe',
    buyerEmail: 'john@example.com',
    buyerPhone: '+1234567890',
    amount: 299.99,
    status: 'pending',
    paymentType: 'cod',
    paymentStatus: 'pending',
    shippingAddress: {
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
    },
    items: [
      {
        id: '1',
        name: 'Wireless Headphones',
        image: '/placeholder.svg?height=60&width=60',
        quantity: 1,
        price: 299.99,
        sku: 'WH-001',
      },
    ],
    timeline: [],
  },
  {
    id: 'ORD-002',
    date: '2024-01-14',
    buyerName: 'Sarah Chen',
    buyerEmail: 'sarah@example.com',
    buyerPhone: '+1234567891',
    amount: 199.99,
    status: 'shipped',
    paymentType: 'card',
    paymentStatus: 'paid',
    shippingAddress: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90210',
      country: 'USA',
    },
    items: [
      {
        id: '2',
        name: 'Smart Watch',
        image: '/placeholder.svg?height=60&width=60',
        quantity: 1,
        price: 199.99,
        sku: 'SW-001',
      },
    ],
    timeline: [],
  },
  {
    id: 'ORD-003',
    date: '2024-01-13',
    buyerName: 'Mike Johnson',
    buyerEmail: 'mike@example.com',
    buyerPhone: '+1234567892',
    amount: 49.99,
    status: 'delivered',
    paymentType: 'paypal',
    paymentStatus: 'paid',
    shippingAddress: {
      street: '789 Pine St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      country: 'USA',
    },
    items: [
      {
        id: '3',
        name: 'Laptop Stand',
        image: '/placeholder.svg?height=60&width=60',
        quantity: 1,
        price: 49.99,
        sku: 'LS-001',
      },
    ],
    timeline: [],
  },
  {
    id: 'ORD-004',
    date: '2024-01-12',
    buyerName: 'Emily Davis',
    buyerEmail: 'emily@example.com',
    buyerPhone: '+1234567893',
    amount: 19.99,
    status: 'cancelled',
    paymentType: 'cod',
    paymentStatus: 'failed',
    shippingAddress: {
      street: '321 Elm St',
      city: 'Houston',
      state: 'TX',
      zipCode: '77001',
      country: 'USA',
    },
    items: [
      {
        id: '4',
        name: 'USB-C Cable',
        image: '/placeholder.svg?height=60&width=60',
        quantity: 1,
        price: 19.99,
        sku: 'UC-001',
      },
    ],
    timeline: [],
  },
  {
    id: 'ORD-005',
    date: '2024-01-11',
    buyerName: 'Alex Wilson',
    buyerEmail: 'alex@example.com',
    buyerPhone: '+1234567894',
    amount: 24.99,
    status: 'pending',
    paymentType: 'card',
    paymentStatus: 'paid',
    shippingAddress: {
      street: '654 Maple Ave',
      city: 'Phoenix',
      state: 'AZ',
      zipCode: '85001',
      country: 'USA',
    },
    items: [
      {
        id: '5',
        name: 'Phone Case',
        image: '/placeholder.svg?height=60&width=60',
        quantity: 1,
        price: 24.99,
        sku: 'PC-001',
      },
    ],
    timeline: [],
  },
  {
    id: 'ORD-002',
    date: '2024-01-14',
    buyerName: 'Sarah Chen',
    buyerEmail: 'sarah@example.com',
    buyerPhone: '+1234567891',
    amount: 199.99,
    status: 'shipped',
    paymentType: 'card',
    paymentStatus: 'paid',
    shippingAddress: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90210',
      country: 'USA',
    },
    items: [
      {
        id: '2',
        name: 'Smart Watch',
        image: '/placeholder.svg?height=60&width=60',
        quantity: 1,
        price: 199.99,
        sku: 'SW-001',
      },
    ],
    timeline: [],
  },
  {
    id: 'ORD-002',
    date: '2024-01-14',
    buyerName: 'Sarah Chen',
    buyerEmail: 'sarah@example.com',
    buyerPhone: '+1234567891',
    amount: 199.99,
    status: 'shipped',
    paymentType: 'card',
    paymentStatus: 'paid',
    shippingAddress: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90210',
      country: 'USA',
    },
    items: [
      {
        id: '2',
        name: 'Smart Watch',
        image: '/placeholder.svg?height=60&width=60',
        quantity: 1,
        price: 199.99,
        sku: 'SW-001',
      },
    ],
    timeline: [],
  },
  {
    id: 'ORD-002',
    date: '2024-01-14',
    buyerName: 'Sarah Chen',
    buyerEmail: 'sarah@example.com',
    buyerPhone: '+1234567891',
    amount: 199.99,
    status: 'shipped',
    paymentType: 'card',
    paymentStatus: 'paid',
    shippingAddress: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90210',
      country: 'USA',
    },
    items: [
      {
        id: '2',
        name: 'Smart Watch',
        image: '/placeholder.svg?height=60&width=60',
        quantity: 1,
        price: 199.99,
        sku: 'SW-001',
      },
    ],
    timeline: [],
  },
  {
    id: 'ORD-002',
    date: '2024-01-14',
    buyerName: 'Sarah Chen',
    buyerEmail: 'sarah@example.com',
    buyerPhone: '+1234567891',
    amount: 199.99,
    status: 'shipped',
    paymentType: 'card',
    paymentStatus: 'paid',
    shippingAddress: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90210',
      country: 'USA',
    },
    items: [
      {
        id: '2',
        name: 'Smart Watch',
        image: '/placeholder.svg?height=60&width=60',
        quantity: 1,
        price: 199.99,
        sku: 'SW-001',
      },
    ],
    timeline: [],
  },
  {
    id: 'ORD-002',
    date: '2024-01-14',
    buyerName: 'Sarah Chen',
    buyerEmail: 'sarah@example.com',
    buyerPhone: '+1234567891',
    amount: 199.99,
    status: 'shipped',
    paymentType: 'card',
    paymentStatus: 'paid',
    shippingAddress: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90210',
      country: 'USA',
    },
    items: [
      {
        id: '2',
        name: 'Smart Watch',
        image: '/placeholder.svg?height=60&width=60',
        quantity: 1,
        price: 199.99,
        sku: 'SW-001',
      },
    ],
    timeline: [],
  },
  {
    id: 'ORD-002',
    date: '2024-01-14',
    buyerName: 'Sarah Chen',
    buyerEmail: 'sarah@example.com',
    buyerPhone: '+1234567891',
    amount: 199.99,
    status: 'shipped',
    paymentType: 'card',
    paymentStatus: 'paid',
    shippingAddress: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90210',
      country: 'USA',
    },
    items: [
      {
        id: '2',
        name: 'Smart Watch',
        image: '/placeholder.svg?height=60&width=60',
        quantity: 1,
        price: 199.99,
        sku: 'SW-001',
      },
    ],
    timeline: [],
  },
];


