

export const PRODUCTS = [
  {
    id: 1,
    name: 'Wireless Bluetooth Headphones',
    category: 'Electronics',
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.5,
    reviews: 128,
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
    featured: true,
    brand: 'TechSound',
  },
  {
    id: 2,
    name: 'Organic Cotton T-Shirt',
    category: 'Clothing',
    price: 24.99,
    originalPrice: 29.99,
    rating: 4.2,
    reviews: 89,
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
    featured: false,
    brand: 'EcoWear',
  },
  {
    id: 3,
    name: 'Smart Fitness Watch',
    category: 'Electronics',
    price: 199.99,
    originalPrice: 249.99,
    rating: 4.7,
    reviews: 256,
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
    featured: true,
    brand: 'FitTech',
  },
  {
    id: 4,
    name: 'Leather Crossbody Bag',
    category: 'Accessories',
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.4,
    reviews: 67,
    image: '/placeholder.svg?height=300&width=300',
    inStock: false,
    featured: false,
    brand: 'StyleCraft',
  },
  {
    id: 5,
    name: 'Ceramic Coffee Mug Set',
    category: 'Home & Kitchen',
    price: 34.99,
    originalPrice: 44.99,
    rating: 4.6,
    reviews: 143,
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
    featured: false,
    brand: 'HomeEssentials',
  },
  {
    id: 6,
    name: 'Running Sneakers',
    category: 'Clothing',
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.3,
    reviews: 201,
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
    featured: true,
    brand: 'SportMax',
  },
  {
    id: 7,
    name: 'Portable Phone Charger',
    category: 'Electronics',
    price: 39.99,
    originalPrice: 49.99,
    rating: 4.1,
    reviews: 94,
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
    featured: false,
    brand: 'PowerUp',
  },
  {
    id: 8,
    name: 'Scented Candle Collection',
    category: 'Home & Kitchen',
    price: 54.99,
    originalPrice: 69.99,
    rating: 4.8,
    reviews: 312,
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
    featured: false,
    brand: 'AromaBliss',
  },
];
